[package]
name = "lieutenant"
version = "0.1.0"
authors = ["= <jacob@rosborg.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0"
anyhow = "1.0"
regex = "1.4"
lazy_static = "1.4"